[general]
import = ["~/.config/alacritty/cyberdream.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14.0                # Set your preferred font size
offset = { x = 0, y = 0 }  # Fine-tune alignment if needed
glyph_offset = { x = 0, y = 0 }  # Glyph-specific offset

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
unfocused_hollow = true
